import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/header";
import Footer from "@/components/footer";
import { Poppins } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "600", "700"], subsets: ["latin"] });

export const metadata = {
  title: "GPA CHEBY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header></Header>
        <div className="min-h-screen">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
